"""Creating course table

Revision ID: 01fe88c7f556
Revises: 1fdec7f60d60
Create Date: 2020-08-19 18:33:40.695702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fe88c7f556'
down_revision = '1fdec7f60d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.Column('end_time', sa.String(length=120), nullable=False),
    sa.Column('day', sa.String(length=120), nullable=False),
    sa.Column('number_of_tutors', sa.Integer(), nullable=False),
    sa.Column('Lecture_employee_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Lecture_employee_number'], ['lecture.employee_number'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
