"""added enrollment key to course table

Revision ID: 07486037c42e
Revises: d9cf24d10229
Create Date: 2020-08-25 13:23:44.468098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07486037c42e'
down_revision = 'd9cf24d10229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('key', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'key')
    # ### end Alembic commands ###
