"""empty message

Revision ID: 1fdec7f60d60
Revises: 7bf5cfbd5156
Create Date: 2020-08-18 23:11:06.700191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fdec7f60d60'
down_revision = '7bf5cfbd5156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'year_of_study')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('year_of_study', mysql.VARCHAR(length=2), nullable=False))
    # ### end Alembic commands ###
