"""removing group column in user , adding status to tutor

Revision ID: 2bae9fe2ae54
Revises: 86ec5f146f1d
Create Date: 2020-08-24 11:35:56.789315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bae9fe2ae54'
down_revision = '86ec5f146f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_group', table_name='user')
    op.drop_column('user', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('ix_user_group', 'user', ['group'], unique=False)
    op.drop_column('tutor', 'status')
    # ### end Alembic commands ###
