"""empty message

Revision ID: 7bf5cfbd5156
Revises: a6d1b259ef1b
Create Date: 2020-08-18 23:03:59.999694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bf5cfbd5156'
down_revision = 'a6d1b259ef1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_number', sa.String(length=10), nullable=False),
    sa.Column('year_of_study', sa.String(length=2), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_number')
    )
    op.add_column('tutor', sa.Column('id_number', sa.String(length=10), nullable=False))
    op.drop_column('tutor', 'student_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('student_number', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('tutor', 'id_number')
    op.drop_table('student')
    # ### end Alembic commands ###
