"""create all the tables at once

Revision ID: 86ec5f146f1d
Revises: 
Create Date: 2020-08-24 10:32:39.061887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ec5f146f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_user_create_date'), 'user', ['create_date'], unique=False)
    op.create_index(op.f('ix_user_group'), 'user', ['group'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('lecture',
    sa.Column('employee_number', sa.String(length=10), nullable=False),
    sa.Column('office_number', sa.String(length=10), nullable=True),
    sa.Column('telephone_number', sa.String(length=12), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_number'),
    sa.UniqueConstraint('office_number'),
    sa.UniqueConstraint('telephone_number')
    )
    op.create_table('student',
    sa.Column('student_number', sa.String(length=10), nullable=False),
    sa.Column('year_of_study', sa.String(length=2), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_number')
    )
    op.create_table('tutor',
    sa.Column('id_number', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.String(length=60), nullable=True),
    sa.Column('account_number', sa.String(length=60), nullable=True),
    sa.Column('bank_name', sa.String(length=60), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_number'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('course',
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.Column('end_time', sa.String(length=120), nullable=False),
    sa.Column('day', sa.String(length=120), nullable=False),
    sa.Column('number_of_tutors', sa.Integer(), nullable=False),
    sa.Column('Lecture_employee_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Lecture_employee_number'], ['lecture.employee_number'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('students_and_courses',
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['student_number'], ['student.student_number'], ),
    sa.PrimaryKeyConstraint('student_number', 'course_code')
    )
    op.create_table('tutors_and_courses',
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['id_number'], ['tutor.id_number'], ),
    sa.PrimaryKeyConstraint('id_number', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutors_and_courses')
    op.drop_table('students_and_courses')
    op.drop_table('course')
    op.drop_table('tutor')
    op.drop_table('student')
    op.drop_table('lecture')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_group'), table_name='user')
    op.drop_index(op.f('ix_user_create_date'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
