"""added a many-to-many relationship between student and course tables

Revision ID: 9376c1333389
Revises: 01fe88c7f556
Create Date: 2020-08-22 04:22:19.294675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9376c1333389'
down_revision = '01fe88c7f556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_and_courses',
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['student_number'], ['student.student_number'], ),
    sa.PrimaryKeyConstraint('student_number', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_and_courses')
    # ### end Alembic commands ###
