"""remove unique key constraint on tutor table

Revision ID: d9cf24d10229
Revises: 2bae9fe2ae54
Create Date: 2020-08-24 13:33:36.922935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cf24d10229'
down_revision = '2bae9fe2ae54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_number', table_name='tutor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('account_number', 'tutor', ['account_number'], unique=True)
    # ### end Alembic commands ###
