"""empty message

Revision ID: ec462374fc4d
Revises: 
Create Date: 2020-08-07 13:57:51.292474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec462374fc4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_user_create_date'), 'user', ['create_date'], unique=False)
    op.create_index(op.f('ix_user_group'), 'user', ['group'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('lecture',
    sa.Column('employee_number', sa.String(length=10), nullable=False),
    sa.Column('office_number', sa.String(length=10), nullable=False),
    sa.Column('telephone_number', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('employee_number'),
    sa.UniqueConstraint('office_number'),
    sa.UniqueConstraint('telephone_number')
    )
    op.create_table('tutor',
    sa.Column('student_number', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.String(length=60), nullable=False),
    sa.Column('account_number', sa.String(length=60), nullable=False),
    sa.Column('bank_name', sa.String(length=60), nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('year_of_study', sa.String(length=2), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_number'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor')
    op.drop_table('lecture')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_group'), table_name='user')
    op.drop_index(op.f('ix_user_create_date'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
