"""addded forum table

Revision ID: 327953343737
Revises: 12229c4b8429
Create Date: 2020-09-24 21:53:22.224112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327953343737'
down_revision = '12229c4b8429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('forum_recipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'forum', ['forum_recipt_id'], ['forum_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'forum_recipt_id')
    # ### end Alembic commands ###
