"""adding register table

Revision ID: 95281c517912
Revises: 8f74c06b992d
Create Date: 2020-09-02 10:29:16.928002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95281c517912'
down_revision = '8f74c06b992d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=50), nullable=False),
    sa.Column('session', sa.DateTime(), nullable=True),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('tutor', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['tutor'], ['tutor.id_number'], ),
    sa.PrimaryKeyConstraint('register_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    # ### end Alembic commands ###
