"""added otp column to tutor table

Revision ID: c188124c4097
Revises: 796c1cef8c89
Create Date: 2020-09-07 08:20:47.259361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c188124c4097'
down_revision = '796c1cef8c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('otp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'otp')
    # ### end Alembic commands ###
