"""adding status column to application table

Revision ID: f12440e39493
Revises: 95281c517912
Create Date: 2020-09-03 16:16:45.291515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12440e39493'
down_revision = '95281c517912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
